<?php

namespace Osd\RetireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WorkerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkerRepository extends EntityRepository
{
    public function findByPersonDetails($omang, $WorkerName, 
            $workerSurname, $birthDay, $dateOfEmployment,$fileNumber, $workerStatus = null){
        $createQuery = 'SELECT w FROM OsdRetireBundle:Worker w 
                   WHERE w.omang LIKE :omang
                   AND w.workerName LIKE :WorkerName
                   AND w.workerSurname LIKE :workerSurname';
         if ($birthDay != '')
            $createQuery .= ' AND w.birthDay LIKE :birthDay';
         if ($workerStatus != '') $createQuery .= ' AND w.aIdWorkerStatus = :aIdWorkerStatus';
         if ($dateOfEmployment != '')
            $createQuery .= 'AND w.dateOfEmployment LIKE :dateOfEmployment';
         if ($fileNumber !='')
             $createQuery .= ' AND w.fileNumber like :fileNumber';
        $qqq = $this->getEntityManager()
               ->createQuery($createQuery)
               ->setParameter('omang', '%'.$omang.'%')
               ->setParameter('WorkerName', '%'.$WorkerName.'%')
               ->setParameter('workerSurname', '%'.$workerSurname.'%');
        if ($birthDay != '') $qqq = 
                $qqq->setParameter('birthDay', '%'.$birthDay->format('Y-m-d').'%');
        if ($dateOfEmployment != '') $qqq = $qqq->setParameter('dateOfEmployment'
                , '%'.$dateOfEmployment->format('Y-m-d').'%');
        if ($fileNumber != '') $qqq->setParameter ('fileNumber', '%'.$fileNumber.'%');
        if ($workerStatus != '') $qqq->setParameter ('aIdWorkerStatus', $workerStatus);
        $qqq = $qqq->getResult();
       return $qqq;
   }
   public function findBycountTotalWorkers (){
       $query = $this->createQueryBuilder('Worker')->select('COUNT(Worker)');
       $total = $query->getQuery()->getSingleScalarResult();
       return $total;
   }
           
}
           

